/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.FrontOffice.FrontOffice;
import GUI.HousekeepingOffice.HousekeepingOffice;
import GUI.MaintainerOffice.MaintainerOffice;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author TUF_Heat_
 */
public class EventShedule extends javax.swing.JPanel {

    private Home home;
    private FrontOffice frontOffice;
    private HousekeepingOffice housekeepingOffice;
    private MaintainerOffice maintainerOffice;

    /**
     * Creates new form EventShedule
     */
    public EventShedule(JFrame jFrame) {
        initComponents();

        if (jFrame.getClass().getName().endsWith("Home")) {
            this.home = (Home) jFrame;
        } else if (jFrame.getClass().getName().endsWith("FrontOffice")) {
            this.frontOffice = (FrontOffice) jFrame;
        } else if (jFrame.getClass().getName().endsWith("HousekeepingOffice")) {
            this.housekeepingOffice = (HousekeepingOffice) jFrame;
        } else if (jFrame.getClass().getName().endsWith("MaintainerOffice")) {
            this.maintainerOffice = (MaintainerOffice) jFrame;
        }

        loadEvents("today");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(1000, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Place", "Starting Date", "Starting Time", "Ending Date", "Ending Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel1.setText("Event Shedule");

        jToggleButton1.setFont(new java.awt.Font("Microsoft Uighur", 0, 24)); // NOI18N
        jToggleButton1.setText("Today");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 667, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (home != null) {
            this.home.removePanel();
        } else if (frontOffice != null) {
            this.frontOffice.removePanel();
        } else if (housekeepingOffice != null) {
            this.housekeepingOffice.removePanel();
        } else if (maintainerOffice != null) {
            this.maintainerOffice.removePanel();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            jToggleButton1.setText("This Month");
            loadEvents("month");
        } else {
            jToggleButton1.setText("Today");
            loadEvents("today");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    private void loadEvents(String sort) {

        if ("today".equals(sort)) {
            ResultSet resultSet;
            try {
                resultSet = MySQL.executeSearch("SELECT * FROM `event_schedule` WHERE `start_date` = CURDATE()");
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (resultSet.next()) {
                    Vector<String> vector = new Vector<>();
                    vector.add(resultSet.getString("event_name"));
                    vector.add(resultSet.getString("place"));
                    vector.add(resultSet.getString("start_date"));
                    vector.add(resultSet.getString("start_time"));
                    vector.add(resultSet.getString("end_date"));
                    vector.add(resultSet.getString("end_time"));

                    model.addRow(vector);
                }
            } catch (Exception ex) {
                Logger.getLogger(EventShedule.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if ("month".equals(sort)) {
            ResultSet resultSet;
            try {
                resultSet = MySQL.executeSearch("SELECT * FROM `event_schedule` WHERE YEAR(`start_date`) = YEAR(CURDATE()) AND MONTH(`start_date`) = MONTH(CURDATE());");
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (resultSet.next()) {
                    Vector<String> vector = new Vector<>();
                    vector.add(resultSet.getString("event_name"));
                    vector.add(resultSet.getString("place"));
                    vector.add(resultSet.getString("start_date"));
                    vector.add(resultSet.getString("start_time"));
                    vector.add(resultSet.getString("end_date"));
                    vector.add(resultSet.getString("end_time"));

                    model.addRow(vector);
                }
            } catch (Exception ex) {
                Logger.getLogger(EventShedule.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}

