/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.FrontOffice.FrontOffice;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author TUF_Heat_
 */
public class RoomAllocation extends javax.swing.JPanel {

    private Home home;
    private FrontOffice frontOffice;

    /**
     * Creates new form RoomAllocation
     */
    public RoomAllocation(Home home) {
        initComponents();
        this.home = home;
        loadRooms("");
    }

    public RoomAllocation(FrontOffice frontOffice) {
        initComponents();
        this.frontOffice = frontOffice;
        loadRooms("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Guest name", "Arrival Date", "Arrival Time", "Depature Date", "Depature Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Uighur", 1, 24)); // NOI18N
        jLabel1.setText("Room Allocation");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Search by Room number");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (home != null) {
            this.home.removePanel();
        } else if (frontOffice != null) {
            this.frontOffice.removePanel();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        loadRooms(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void loadRooms(String room) {
        if (!room.isEmpty()) {
            try {
                ResultSet resultSet = MySQL.executeSearch("SELECT `rooms`.`room_id`, `room_no`, `room_status`, `guest_name`, DATE(`arrival_date_time`) AS `a_date`, TIME(`arrival_date_time`) AS `a_time`, DATE(`departure_date_time`) AS `d_date`, TIME(`departure_date_time`) AS `d_time` FROM `rooms` "
                        + "INNER JOIN `guest_stays` "
                        + "WHERE `guest_stays`.room_id = `rooms`.room_id AND `rooms`.`room_no` = '"+room+"'");
                
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (resultSet.next()) {
                    Vector<String> vector = new Vector<>();
                    vector.add(resultSet.getString("room_no"));
                    vector.add(resultSet.getString("guest_name"));
                    vector.add(resultSet.getString("a_date"));
                    vector.add(resultSet.getString("a_time"));
                    vector.add(resultSet.getString("d_date"));
                    vector.add(resultSet.getString("d_time"));
                    vector.add(resultSet.getString("room_status"));

                    model.addRow(vector);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                ResultSet resultSet = MySQL.executeSearch("SELECT `rooms`.`room_id`, `room_no`, `room_status`, `guest_name`, DATE(`arrival_date_time`) AS `a_date`, TIME(`arrival_date_time`) AS `a_time`, DATE(`departure_date_time`) AS `d_date`, TIME(`departure_date_time`) AS `d_time` FROM `rooms` "
                        + "INNER JOIN `guest_stays` WHERE `guest_stays`.room_id = `rooms`.room_id");
                
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                while (resultSet.next()) {
                    Vector<String> vector = new Vector<>();
                    vector.add(resultSet.getString("room_no"));
                    vector.add(resultSet.getString("guest_name"));
                    vector.add(resultSet.getString("a_date"));
                    vector.add(resultSet.getString("a_time"));
                    vector.add(resultSet.getString("d_date"));
                    vector.add(resultSet.getString("d_time"));
                    vector.add(resultSet.getString("room_status"));

                    model.addRow(vector);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
