/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.FrontOffice;

import GUI.HousekeepingOffice.HousekeepingOffice;
import GUI.HumanresourcesOffice.HumanresourceOffice;
import GUI.MaintainerOffice.MaintainerOffice;
import GUI.Resturent.RestunrantOffice;
import javax.swing.JFrame;

/**
 *
 * @author TUF_Heat_
 */
public class WorkersList extends javax.swing.JPanel {

    private FrontOffice frontOffice;
    private RestunrantOffice restunrantOffice;
    private HousekeepingOffice housekeepingOffice;
    private MaintainerOffice maintainerOffice;
    private HumanresourceOffice humanresourceOffice;

    /**
     * Creates new form WorkersList
     */
    public WorkersList(JFrame jFrame) {
        initComponents();
        if (jFrame.getClass().getName().endsWith("FrontOffice")) {
            this.frontOffice = (FrontOffice) jFrame;
        } else if (jFrame.getClass().getName().endsWith("RestunrantOffice")) {
            this.restunrantOffice = (RestunrantOffice) jFrame;
        } else if (jFrame.getClass().getName().endsWith("HousekeepingOffice")) {
            this.housekeepingOffice = (HousekeepingOffice) jFrame;
        } else if (jFrame.getClass().getName().endsWith("MaintainerOffice")) {
            this.maintainerOffice = (MaintainerOffice) jFrame;
        }else if (jFrame.getClass().getName().endsWith("HumanresourceOffice")) {
            this.humanresourceOffice = (HumanresourceOffice) jFrame;
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Workers List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 862, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Name", "Start at", "End at", "Shift", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.frontOffice != null) {
            this.frontOffice.removePanel();
        } else if (this.restunrantOffice != null) {
            this.restunrantOffice.removePanel();
        } else if (this.housekeepingOffice != null) {
            this.housekeepingOffice.removePanel();
        } else if (this.maintainerOffice != null) {
            this.maintainerOffice.removePanel();
        }else if (this.humanresourceOffice != null) {
            this.humanresourceOffice.removePanel();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            if (jTable1.getSelectedRow() != -1) {
                if (this.frontOffice != null) {
                    new MonthlyShedule(this.frontOffice, true).setVisible(true);
                } else if (this.restunrantOffice != null) {
                    new MonthlyShedule(this.restunrantOffice, true).setVisible(true);
                } else if (this.housekeepingOffice != null) {
                    new MonthlyShedule(this.housekeepingOffice, true).setVisible(true);
                } else if (this.maintainerOffice != null) {
                    new MonthlyShedule(this.maintainerOffice, true).setVisible(true);
                }else if (this.humanresourceOffice != null) {
                    new MonthlyShedule(this.humanresourceOffice, true).setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
